[versions]
agp = "8.13.0"
kotlin = "2.2.0"
ksp ="2.0.21-1.0.27"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
appcompat = "1.7.0"

#network
retrofit = "2.9.0"
gson = "2.10.1"
okhttp = "4.12.0"

#logger
logger = "2.2.0"
#koin
koin = "3.5.3"
koinWork = "3.5.3"
#room
room = "2.8.3"
#rtsp
#rtsp ="v5.1.6-swdecoder"
rtsp ="5.1.0" #com.github.am3n:rtsp-client-android  원본
#common android
lifecycle = "2.8.6"
navigationFragmentKtx = "2.9.5"
navigationUiKtx = "2.9.5"
navigationFragmentKtxVersion = "2.9.6"
navigationUiKtxVersion = "2.9.6"


tedPermission = "3.4.2"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }

orhanobut-logger = { module = "com.orhanobut:logger", version.ref = "logger"}


#rtsp
#rtsp-client-android = { module = "com.github.p2achAI:rtsp-client-android", version.ref = "rtsp" } 원래 p2achai rtsp
rtsp-client-android = { module = "com.github.am3n:rtsp-client-android", version.ref = "rtsp" }
#koin
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-workmanager = { module = "io.insert-koin:koin-androidx-workmanager", version.ref = "koinWork" }
#network
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

#room
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

#android common
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtxVersion" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtxVersion" }

kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

ted-permission ={module = "io.github.ParkSangGwon:tedpermission-normal", version.ref = "tedPermission"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
androidx-room = { id = "androidx.room", version.ref = "room" }


